insert into CAR  values (9373, 'SL-Class', 'Mercedes-Benz', 'Electric', 'SUV');
insert into CAR  values (2821,'B-Series', 'Mazda', 'Electric', 'SUV');
insert into CAR  values (8592, 'Skylark', 'Buick', 'Electric', 'Luxury');
insert into CAR  values (4073, 'Accord', 'Honda', 'Hybrid', 'Luxury');
insert into CAR  values (8822, 'G-Series G20', 'Chevrolet', 'Electric', 'SUV');
insert into CAR  values (9330, 'Coachbuilder', 'Buick', 'Gas', 'CityCar');
insert into CAR  values (2020, 'Express', 'Chevrolet', 'Gas', 'SUV');
insert into CAR  values (5438, 'Brooklands', 'Bentley', 'Electric', 'Luxury');
insert into CAR  values (5627, '3500', 'Chevrolet', 'Gas', 'CityCar');
insert into CAR  values (6875, '928', 'Porsche', 'Hybrid', 'Luxury');
insert into CAR  values (5542, '458 Italia', 'Ferrari', 'Gas', 'Luxury');
insert into CAR  values (9010, 'Focus', 'Ford', 'Electric', 'SUV');
insert into CAR  values (4052, 'Mighty Max', 'Mitsubishi', 'Hybrid', 'SUV');
insert into CAR  values (8240, 'Cougar', 'Mercury', 'Hybrid', 'SUV');
insert into CAR  values (9669, 'FX', 'Infiniti', 'Electric', 'CityCar');
insert into CAR  values (9970, 'Jetta', 'Volkswagen', 'Gas', 'SUV');
insert into CAR  values (9300, 'Express 1500', 'Chevrolet', 'Hybrid', 'Luxury');
insert into CAR  values (3672, 'Regal', 'Buick', 'Gas', 'CityCar');
insert into CAR  values (6617, 'SJ', 'Suzuki', 'Electric', 'SUV');
insert into CAR  values (5859, 'MX-5', 'Mazda', 'Electric', 'CityCar');
insert into CAR  values (9925, 'LX', 'Lexus', 'Electric', 'SUV');
insert into CAR  values (7335, 'Spyder', 'Maserati', 'Gas', 'Luxury');
insert into CAR  values (9028, 'Somerset', 'Buick', 'Gas', 'Luxury');
insert into CAR  values (2796, 'NSX', 'Acura', 'Electric', 'Luxury');
insert into CAR  values (8438, 'RX-7', 'Mazda', 'Electric', 'CityCar');
insert into CAR  values (8846, '4Runner', 'Toyota', 'Hybrid', 'Luxury');
insert into CAR  values (8487, '911', 'Porsche', 'Gas', 'SUV');
insert into CAR  values (8375, 'S4', 'Audi', 'Electric', 'Luxury');
insert into CAR  values (6771, 'Fusion', 'Ford', 'Electric', 'CityCar');
insert into CAR  values (1875, 'Crossfire Roadster', 'Chrysler', 'Gas', 'CityCar');
